# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDownAndOutCall <- function(S_ = 95, K_ = 100, r_ = 0.07, sigma_ = 0.24, L_ = 80, t_ = 0.75, NumberOfPaths_ = 1000L) {
    .Call(`_montecarlo426246_getDownAndOutCall`, S_, K_, r_, sigma_, L_, t_, NumberOfPaths_)
}

rcpp_hello_world <- function() {
    .Call(`_montecarlo426246_rcpp_hello_world`)
}

