// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getDownAndOutCall
double getDownAndOutCall(double S_, double K_, double r_, double sigma_, double L_, double t_, int NumberOfPaths_);
RcppExport SEXP _montecarlo426246_getDownAndOutCall(SEXP S_SEXP, SEXP K_SEXP, SEXP r_SEXP, SEXP sigma_SEXP, SEXP L_SEXP, SEXP t_SEXP, SEXP NumberOfPaths_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type S_(S_SEXP);
    Rcpp::traits::input_parameter< double >::type K_(K_SEXP);
    Rcpp::traits::input_parameter< double >::type r_(r_SEXP);
    Rcpp::traits::input_parameter< double >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< double >::type L_(L_SEXP);
    Rcpp::traits::input_parameter< double >::type t_(t_SEXP);
    Rcpp::traits::input_parameter< int >::type NumberOfPaths_(NumberOfPaths_SEXP);
    rcpp_result_gen = Rcpp::wrap(getDownAndOutCall(S_, K_, r_, sigma_, L_, t_, NumberOfPaths_));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _montecarlo426246_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_montecarlo426246_getDownAndOutCall", (DL_FUNC) &_montecarlo426246_getDownAndOutCall, 7},
    {"_montecarlo426246_rcpp_hello_world", (DL_FUNC) &_montecarlo426246_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_montecarlo426246(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
